<!DOCTYPE school [
<!ELEMENT school (student+)>
<!ELEMENT student (id, name, age, status)>
<!ELEMENT id (#REQUIRED)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT status (#IMPLIED)>
]>
<school>
    <student id=a1>
        <name>Juan Perez</name>
        <age>22</age>
        <status></status>
    </student>
    <student id=a2>
        <name>Maria Gonzalez</name>
        <age>20</age>
        <status></status>
    </student>
    <student id=a3>
        <name>Carlos Rodrigez</name>
        <age>21</age>
        <status></status>
    </student>
    <student id=a4>
        <name>Laura Martinez</name>
        <age>23</age>
        <status></status>
    </student>
    <student id=a5>
        <name>Andres Lopez</name>
        <age>19</age>
        <status></status>
    </student>
</school>